# Generated by Django 4.2.2 on 2023-07-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id_booking', models.SmallAutoField(primary_key=True, serialize=False)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('price', models.IntegerField()),
                ('booking_date', models.DateTimeField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookingTenant',
            fields=[
                ('id_booking_tenant', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'booking_tenant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('base_price', models.SmallIntegerField()),
                ('min_nights_amount', models.IntegerField()),
                ('is_available', models.IntegerField()),
            ],
            options={
                'db_table': 'calendar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id_discount', models.AutoField(primary_key=True, serialize=False)),
                ('nights_amount', models.IntegerField()),
                ('discount', models.IntegerField()),
            ],
            options={
                'db_table': 'discount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id_flat', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=100)),
                ('add_date', models.DateField()),
                ('edit_date', models.DateField()),
                ('link_sites', models.CharField(max_length=45)),
                ('link_tenants', models.CharField(max_length=45)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'flat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlatDiscount',
            fields=[
                ('id_flat_discount', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'flat_discount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlatSource',
            fields=[
                ('id_flat_source', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'flat_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id_landlord', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=15)),
                ('registration_date', models.DateField()),
                ('edit_date', models.DateField()),
            ],
            options={
                'db_table': 'landlord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id_source', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('phone', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tenant',
                'managed': False,
            },
        ),
    ]
