# Generated by Django 4.2.2 on 2023-07-12 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_alter_booking_options_alter_bookingtenant_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='email',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='name',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='password',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='id_flat',
            field=models.ForeignKey(db_column='id_flat', default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.flat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='id_source',
            field=models.ForeignKey(db_column='id_source', default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.source'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='id_status',
            field=models.ForeignKey(db_column='id_status', default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='tenant',
            field=models.ManyToManyField(related_name='tenant', through='booking.BookingTenant', to='booking.tenant'),
        ),
        migrations.AddField(
            model_name='bookingtenant',
            name='id_booking',
            field=models.ForeignKey(db_column='id_booking', default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingtenant',
            name='phone',
            field=models.ForeignKey(db_column='phone', default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='id_flat',
            field=models.ForeignKey(db_column='id_flat', default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.flat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='flat',
            field=models.ManyToManyField(related_name='fl_disc', through='booking.FlatDiscount', to='booking.flat'),
        ),
        migrations.AddField(
            model_name='flat',
            name='discount',
            field=models.ManyToManyField(related_name='disc', through='booking.FlatDiscount', to='booking.discount'),
        ),
        migrations.AddField(
            model_name='flat',
            name='id_landlord',
            field=models.ForeignKey(db_column='id_landlord', default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.landlord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='source',
            field=models.ManyToManyField(related_name='sour', through='booking.FlatSource', to='booking.source'),
        ),
        migrations.AddField(
            model_name='flatdiscount',
            name='id_discount',
            field=models.ForeignKey(db_column='id_discount', default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.discount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flatdiscount',
            name='id_flat',
            field=models.ForeignKey(db_column='id_flat', default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.flat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flatsource',
            name='id_flat',
            field=models.ForeignKey(db_column='id_flat', default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.flat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flatsource',
            name='id_source',
            field=models.ForeignKey(db_column='id_source', default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.source'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlord',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='flat',
            field=models.ManyToManyField(related_name='fl_sour', through='booking.FlatSource', to='booking.flat'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='booking',
            field=models.ManyToManyField(related_name='booking', through='booking.BookingTenant', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='add_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='edit_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='edit_date',
            field=models.DateField(auto_now=True),
        ),
    ]
