# Generated by Django 4.2.2 on 2023-07-12 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_remove_booking_discount_remove_landlord_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='id_user',
        ),
        migrations.AlterField(
            model_name='landlord',
            name='id_landlord',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
