# Generated by Django 4.2.2 on 2023-07-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_landlord_id_user_alter_landlord_id_landlord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('date', 'id_flat')},
        ),
    ]
