# Generated by Django 4.2.2 on 2023-07-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_calendar_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='id_date',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
