# Generated by Django 4.2.2 on 2023-07-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_calendar_id_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='id_date',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
