# Generated by Django 4.2.2 on 2023-07-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_calendar_date_alter_calendar_id_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='id_date',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
